### ISSUE TITLE
How to auto login other tab when one tab is logged in react js? #help

### ISSUE THREAD

**Issue by Sathiyamm** [Scarysize/redux-tab-sync#1]
I'm open login page in multiple tabs. 
When I log in to the one tab, I need to login other tabs at the same time in react js.(auto reload or refresh in for other tabs)
Is it possible for using redux-tab-sync?

**Comment by Scarysize** [comment]
This is not a library, just an example implementation showing how you can sync tabs using redux. Check my blog post about it: https://medium.com/@Scarysize/syncing-redux-stores-across-browser-tabs-fff04f975423
